name: Release on PYPI

on:
  workflow_dispatch:
  push:
    tags: [ 'py-*.*.*' ]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      working-directory: sdk/python
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.3
        poetry --version
        poetry config --list
    
    - name: Build package
      working-directory: sdk/python
      run: |
        rm -rf dist/
        echo "=== Poetry configuration ==="
        cat pyproject.toml | head -20
        echo "=== Source directory structure ==="
        find src/ -name "*.py" | head -10
        echo "=== Building package ==="
        poetry build -vvv
    
    - name: Validate package
      working-directory: sdk/python
      run: |
        pip install twine
        echo "=== Listing built files ==="
        ls -la dist/
        echo "=== Checking wheel contents ==="
        python -m zipfile -l dist/*.whl | head -20
        echo "=== Extracting and checking metadata ==="
        python -m zipfile -e dist/*.whl temp_extract/
        find temp_extract/ -name "METADATA" -exec cat {} \; | head -20
        echo "=== Running twine check ==="
        twine check dist/*
    
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0
      with:
        packages-dir: sdk/python/dist
